version: '2'

services:

  mauticdb:
    image: powertic/percona-docker
    container_name: mauticdb
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mkt2022storeofapp
    restart: always
    command:
      --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --sql-mode=""
    networks:
      - mautic-net

  mautic:
    image: mautic/mautic:v4
    container_name: mautic
    links:
      - mauticdb:mysql
    depends_on:
      - mauticdb
    #restart: always
    ports:
      - 80
    labels:
      # - "traefik.frontend.rule=Host:mautic-service.docker.localhost"
      # - traefik.docker.network=proxy
      # - traefik.port=80
      - "traefik.enable=true"
      - "traefik.http.routers.mauticservice.rule=Host(`mautic-service.docker.localhost`)"
      - "traefik.http.routers.mauticservice.entrypoints=web"
      - "traefik.http.services.mauticservice.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
    volumes:
      - ./mautic_data:/var/www/html
    environment:
      - MAUTIC_DB_HOST=mauticdb
      - MYSQL_PORT_3306_TCP=3306
      - MAUTIC_DB_PORT=3306
      - MAUTIC_DB_USER=root
      - MAUTIC_DB_PASSWORD=mautic
      - MAUTIC_DB_NAME=mautic
      - MAUTIC_RUN_CRON_JOBS=true
    networks:
      - proxy
      - mautic-net

volumes:
  mysql_data:
    driver: local
  mautic_data:
    driver: local
networks:
  mautic-net:
    driver: bridge
  proxy:
    external:
      name: proxy